# =========================================================================
# Copyright (C) 2024. Cloud-Device Recommendation System.
# =========================================================================

"""
Negative Sampler for Training with Pairwise Ranking.

This module provides utilities for sampling negative items during training
when the training data contains only positive examples.

Supports two sampling modes:
- Random: uniform sampling from the entire item pool (default)
- Retrieval-based: sampling from per-user hard negative candidate pools
  generated by the retrieval stage

Optimized for high-throughput batch training.
"""

import logging
import numpy as np
import pandas as pd
from typing import List, Set, Any, Optional, Dict

logger = logging.getLogger(__name__)


class NegativeSampler:
    """
    Samples negative items from the item pool for pairwise ranking training.

    Optimized for high-throughput training with:
    - Vectorized batch sampling (no Python loops)
    - Pre-computed numpy arrays for fast lookup
    - Cached feature arrays for GPU transfer
    - Optional per-user candidate pools from retrieval stage
    - Optional popularity-weighted sampling (sample proportional to item frequency^alpha)

    Usage:
        # Random sampling (default)
        sampler = NegativeSampler(item_features_df, item_id_col='cand_item_id')
        neg_item_ids = sampler.sample_negatives_batch(positive_ids, num_negatives=4)

        # Popularity-weighted sampling
        sampler = NegativeSampler(
            item_features_df, item_id_col='cand_item_id',
            item_popularity=popularity_counts, popularity_alpha=0.75,
        )
    """

    def __init__(
        self,
        item_features_df: pd.DataFrame,
        item_id_col: str = 'cand_item_id',
        item_popularity: Optional[Dict] = None,
        popularity_alpha: float = 0.75,
        user_candidates_path: Optional[str] = None,
        user_id_col: Optional[str] = None,
    ):
        """
        Initialize the negative sampler with pre-computed lookup structures.

        Args:
            item_features_df: DataFrame containing item features.
            item_id_col: Column name for item IDs
            item_popularity: Optional dict mapping item_id -> frequency count.
                            If provided, enables popularity-weighted sampling.
            popularity_alpha: Smoothing exponent for popularity weights (0=uniform, 1=proportional).
                            Default 0.75 following word2vec negative sampling convention.
            user_candidates_path: Optional parquet/csv file containing per-user candidate items.
            user_id_col: Optional user/request column in user_candidates_path. If omitted,
                         request_id and impression_id are tried in that order.
        """
        self.item_id_col = item_id_col

        # Ensure DataFrame is indexed by item_id for fast lookup
        if item_features_df.index.name == item_id_col:
            self.item_features_df = item_features_df
        elif item_id_col in item_features_df.columns:
            self.item_features_df = item_features_df.set_index(item_id_col)
        else:
            # Use first column as index
            self.item_features_df = item_features_df

        # Pre-compute numpy arrays for fast sampling
        self.all_item_ids = self.item_features_df.index.to_numpy()
        self.num_items = self.item_features_df.shape[0]

        # Build item_id -> index mapping for fast lookup
        self._item_id_to_idx: Optional[Dict] = None

        # Per-user candidate pools (loaded from retrieval stage)
        self.user_candidates: Optional[Dict[Any, np.ndarray]] = None
        self.has_user_candidates = False
        if user_candidates_path:
            self.user_candidates = self._load_user_candidates(
                user_candidates_path,
                user_id_col=user_id_col,
            )
            self.has_user_candidates = bool(self.user_candidates)

        # Popularity-weighted sampling
        self.sampling_probs: Optional[np.ndarray] = None
        if item_popularity is not None:
            counts = np.array([item_popularity.get(iid, 1.0) for iid in self.all_item_ids], dtype=np.float64)
            counts = np.power(counts, popularity_alpha)
            self.sampling_probs = counts / counts.sum()
            logger.info(f"Popularity-weighted sampling enabled (alpha={popularity_alpha})")

        logger.info(f"NegativeSampler initialized with {self.num_items} items, "
                   f"{self.item_features_df.shape[1]} feature columns pre-cached"
                   f"{', with per-user candidates' if self.has_user_candidates else ''}"
                   f"{', popularity-weighted' if self.sampling_probs is not None else ''}")

    def _load_user_candidates(
        self,
        path: str,
        user_id_col: Optional[str] = None,
    ) -> Dict[Any, np.ndarray]:
        """Load per-user candidate pools from a parquet or csv file."""
        if path.endswith(".parquet"):
            candidates_df = pd.read_parquet(path)
        else:
            candidates_df = pd.read_csv(path)

        candidate_user_col = user_id_col
        if candidate_user_col is None:
            for col in ("request_id", "impression_id", "user_id"):
                if col in candidates_df.columns:
                    candidate_user_col = col
                    break
        if candidate_user_col is None or candidate_user_col not in candidates_df.columns:
            raise ValueError(
                "Could not identify user/request column in candidate file. "
                "Expected one of request_id, impression_id, user_id, or pass user_id_col."
            )

        candidate_item_col = self.item_id_col
        if candidate_item_col not in candidates_df.columns:
            if "item_id" in candidates_df.columns:
                candidate_item_col = "item_id"
            else:
                raise ValueError(
                    f"Could not identify item column in candidate file. "
                    f"Expected {self.item_id_col!r} or 'item_id'."
                )

        user_candidates = {}
        for user_id, group in candidates_df.groupby(candidate_user_col, sort=False):
            item_ids = group[candidate_item_col].dropna().to_numpy()
            if len(item_ids) > 0:
                user_candidates[user_id] = item_ids
        return user_candidates

    def sample_negatives_batch(
        self,
        positive_item_ids: np.ndarray,
        num_negatives: int,
    ) -> np.ndarray:
        """
        Sample negative items for a batch, excluding positives.

        Optimized version that minimizes Python loops.

        Args:
            positive_item_ids: Array of positive item IDs [batch_size]
            num_negatives: Number of negatives per positive

        Returns:
            Array of negative item IDs [batch_size, num_negatives]
        """
        batch_size = len(positive_item_ids)

        # Sample more than needed to handle collisions
        oversample_factor = 2
        total_samples = num_negatives * oversample_factor

        # Random indices into all_item_ids (uniform or popularity-weighted)
        if self.sampling_probs is not None:
            sampled_indices = np.array([
                np.random.choice(self.num_items, size=total_samples, replace=True, p=self.sampling_probs)
                for _ in range(batch_size)
            ])
        else:
            sampled_indices = np.random.randint(
                0, self.num_items,
                size=(batch_size, total_samples)
            )

        # Get corresponding item IDs
        sampled_ids = self.all_item_ids[sampled_indices]

        # Build result array
        result = np.zeros((batch_size, num_negatives), dtype=self.all_item_ids.dtype)

        # Vectorized collision check and selection
        for i in range(batch_size):
            pos_id = positive_item_ids[i]
            candidates = sampled_ids[i]

            # Filter out positive ID (vectorized)
            valid_mask = candidates != pos_id
            valid_candidates = candidates[valid_mask]

            # Take first num_negatives
            if len(valid_candidates) >= num_negatives:
                result[i] = valid_candidates[:num_negatives]
            else:
                # Very rare edge case: pad with any items
                result[i, :len(valid_candidates)] = valid_candidates
                if len(valid_candidates) > 0:
                    result[i, len(valid_candidates):] = valid_candidates[0]
                else:
                    result[i] = self.all_item_ids[:num_negatives]

        return result

    def sample_negatives_batch_from_candidates(
        self,
        user_ids: np.ndarray,
        positive_item_ids: np.ndarray,
        num_negatives: int,
    ) -> np.ndarray:
        """
        Sample negatives from per-user candidate pools, falling back to global sampling.

        Args:
            user_ids: Array of user/request IDs [batch_size]
            positive_item_ids: Array of positive item IDs [batch_size]
            num_negatives: Number of negatives per positive

        Returns:
            Array of negative item IDs [batch_size, num_negatives]
        """
        batch_size = len(positive_item_ids)
        result = np.zeros((batch_size, num_negatives), dtype=self.all_item_ids.dtype)

        if not self.has_user_candidates:
            return self.sample_negatives_batch(positive_item_ids, num_negatives)

        for i, (user_id, pos_id) in enumerate(zip(user_ids, positive_item_ids)):
            candidates = self.user_candidates.get(user_id)
            if candidates is None or len(candidates) == 0:
                result[i] = self.sample_negatives_batch(np.array([pos_id]), num_negatives)[0]
                continue

            valid_candidates = candidates[candidates != pos_id]
            if len(valid_candidates) == 0:
                result[i] = self.sample_negatives_batch(np.array([pos_id]), num_negatives)[0]
                continue

            replace = len(valid_candidates) < num_negatives
            result[i] = np.random.choice(valid_candidates, size=num_negatives, replace=replace)

        return result

    def get_features_by_ids(
        self,
        item_ids: np.ndarray,
    ) -> pd.DataFrame:
        """
        Get features for items by their IDs.

        Args:
            item_ids: Array of item IDs

        Returns:
            pd.DataFrame with item features for the given IDs
        """
        return self.item_features_df.loc[item_ids]
